//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelDelivery
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int FuelID { get; set; }
        public decimal Volume { get; set; }
    
        public virtual Fuel Fuel { get; set; }
    }
}
